### ISSUE TITLE
Remove DS_Store files and maybe the .vscode folder

### ISSUE THREAD

**Issue by BOCOVO** [Dahkenangnon/typescript-express-mongoose-api-boilerplate#1]
- There are quite a few `DS_Store` files in the project. It would be a good idea to delete them and add them to the gitignore.
- Remove perhaps the `.vscode` folder or at least the `.vscode/settings.json` file.

**Comment by Dahkenangnon** [comment]
Hi @BOCOVO. Thank for the issue.

**Comment by BOCOVO** [comment]
@Dahkenangnon 
You haven't deleted them (DS_Store files).
You must also delete them, not just add them to the gitignore files.

**Comment by Dahkenangnon** [comment]
> @Dahkenangnon You haven't deleted them (DS_Store files). You must also delete them, not just add them to the gitignore files.

https://github.com/Dahkenangnon/typescript-express-mongoose-api-boilerplate/commit/905cb5d9e852f2d0af6055e6f0519332e4d4f3b5
